"""Stock KWIPv3 weapon records used by buildable units; tied to the supported hash."""

PROJECTILES = {'SURV_GUNNER_519B70': {'name': 'Machine Gunner — Instant / hitscan',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_GUNNER'],
                        'address': 5348208,
                        'handler': 5109395,
                        'speed': None,
                        'lifetime': None},
 'SURV_GRENADIER_519BB0': {'name': 'Grenadier — Ballistic',
                           'faction': 'Survivors',
                           'units': ['UNIT_SURV_GRENADIER'],
                           'address': 5348272,
                           'handler': 5117869,
                           'speed': 768,
                           'lifetime': None},
 'SURV_FLAMER_519BF0': {'name': 'Flamer — Flame effect',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_FLAMER'],
                        'address': 5348336,
                        'handler': 5122510,
                        'speed': None,
                        'lifetime': None},
 'SURV_ROCKETEER_519C30': {'name': 'Rocketeer — Homing missile',
                           'faction': 'Survivors',
                           'units': ['UNIT_SURV_ROCKETEER'],
                           'address': 5348400,
                           'handler': 5118937,
                           'speed': 1280,
                           'lifetime': 34},
 'SURV_SNIPER_519C70': {'name': 'Laser Rifleman — Direct projectile',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_SNIPER'],
                        'address': 5348464,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'SURV_KAMIKAZE_519CB0': {'name': 'Kamikaze — Self-destruction',
                          'faction': 'Survivors',
                          'units': ['UNIT_SURV_KAMIKAZE'],
                          'address': 5348528,
                          'handler': 5113577,
                          'speed': None,
                          'lifetime': None},
 'MUTE_GUNNER_519D30': {'name': 'Berzerker — Direct projectile',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_GUNNER'],
                        'address': 5348656,
                        'handler': 5116456,
                        'speed': 1024,
                        'lifetime': None},
 'MUTE_GRENADIER_519D70': {'name': 'Rioter — Ballistic',
                           'faction': 'Evolved',
                           'units': ['UNIT_MUTE_GRENADIER'],
                           'address': 5348720,
                           'handler': 5117869,
                           'speed': 768,
                           'lifetime': None},
 'MUTE_FLAMER_519DB0': {'name': 'Pyromaniac — Flame effect',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_FLAMER'],
                        'address': 5348784,
                        'handler': 5122510,
                        'speed': None,
                        'lifetime': None},
 'MUTE_ROCKETEER_519DF0': {'name': 'Homing Bazookoid — Homing missile',
                           'faction': 'Evolved',
                           'units': ['UNIT_MUTE_ROCKETEER'],
                           'address': 5348848,
                           'handler': 5118937,
                           'speed': 1280,
                           'lifetime': 34},
 'MUTE_SNIPER_519E30': {'name': 'Spirit Archer — Direct projectile',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_SNIPER'],
                        'address': 5348912,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'MUTE_KAMIKAZE_519E70': {'name': 'Martyr — Self-destruction',
                          'faction': 'Evolved',
                          'units': ['UNIT_MUTE_KAMIKAZE'],
                          'address': 5348976,
                          'handler': 5113577,
                          'speed': None,
                          'lifetime': None},
 'ROBOT_GUNNER_519F30': {'name': 'Seeder — Direct projectile',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_GUNNER'],
                         'address': 5349168,
                         'handler': 5116456,
                         'speed': 1024,
                         'lifetime': None},
 'ROBOT_GRENADIER_519F70': {'name': 'Pod Launcher — Ballistic',
                            'faction': 'Series 9',
                            'units': ['UNIT_ROBOT_GRENADIER'],
                            'address': 5349232,
                            'handler': 5117869,
                            'speed': 768,
                            'lifetime': None},
 'ROBOT_FLAMER_519FB0': {'name': 'Weed Killer — Flame effect',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_FLAMER'],
                         'address': 5349296,
                         'handler': 5122510,
                         'speed': None,
                         'lifetime': None},
 'ROBOT_ROCKETEER_519FF0': {'name': 'Spore Missile — Homing missile',
                            'faction': 'Series 9',
                            'units': ['UNIT_ROBOT_ROCKETEER'],
                            'address': 5349360,
                            'handler': 5118937,
                            'speed': 1280,
                            'lifetime': 34},
 'ROBOT_SNIPER_51A030': {'name': 'Sterilizer — Direct projectile',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_SNIPER'],
                         'address': 5349424,
                         'handler': 5116456,
                         'speed': 1536,
                         'lifetime': None},
 'ROBOT_KAMIKAZE_51A070': {'name': 'Michaelangelo — Self-destruction',
                           'faction': 'Series 9',
                           'units': ['UNIT_ROBOT_KAMIKAZE'],
                           'address': 5349488,
                           'handler': 5113577,
                           'speed': None,
                           'lifetime': None},
 'SURV_BIKE_51A0B0': {'name': 'Dirt Bike — Instant / hitscan',
                      'faction': 'Survivors',
                      'units': ['UNIT_SURV_BIKE'],
                      'address': 5349552,
                      'handler': 5109395,
                      'speed': None,
                      'lifetime': None},
 'SURV_HOVERBUGGY_51A130': {'name': 'Hover Buggy — Instant / hitscan',
                            'faction': 'Survivors',
                            'units': ['UNIT_SURV_HOVERBUGGY'],
                            'address': 5349680,
                            'handler': 5109395,
                            'speed': None,
                            'lifetime': None},
 'SURV_ATV_51A0F0': {'name': 'ATV — Direct projectile',
                     'faction': 'Survivors',
                     'units': ['UNIT_SURV_ATV'],
                     'address': 5349616,
                     'handler': 5116456,
                     'speed': 1024,
                     'lifetime': None},
 'SURV_ANACONDATANK_51A170': {'name': 'Anaconda Tank — Direct projectile',
                              'faction': 'Survivors',
                              'units': ['UNIT_SURV_ANACONDATANK'],
                              'address': 5349744,
                              'handler': 5116456,
                              'speed': 1536,
                              'lifetime': None},
 'SURV_BARRAGECRAFT_51A1B0': {'name': 'Barrage Craft — Artillery',
                              'faction': 'Survivors',
                              'units': ['UNIT_SURV_BARRAGECRAFT'],
                              'address': 5349808,
                              'handler': 5112123,
                              'speed': None,
                              'lifetime': None},
 'SURV_AUTOCANNONTANK_51A1F0': {'name': 'The Enforcer — Direct projectile',
                                'faction': 'Survivors',
                                'units': ['UNIT_SURV_AUTOCANNONTANK'],
                                'address': 5349872,
                                'handler': 5116456,
                                'speed': 2048,
                                'lifetime': None},
 'SURV_JUGGERNAUT_51A230': {'name': 'Juggernaut — Instant / hitscan',
                            'faction': 'Survivors',
                            'units': ['UNIT_SURV_JUGGERNAUT'],
                            'address': 5349936,
                            'handler': 5109395,
                            'speed': None,
                            'lifetime': None},
 'SURV_JUGGERNAUT_51A270': {'name': 'Juggernaut — Artillery',
                            'faction': 'Survivors',
                            'units': ['UNIT_SURV_JUGGERNAUT'],
                            'address': 5350000,
                            'handler': 5112123,
                            'speed': None,
                            'lifetime': None},
 'MUTE_DIREWOLF_51A2B0': {'name': 'Dire Wolf — Instant / hitscan',
                          'faction': 'Evolved',
                          'units': ['UNIT_MUTE_DIREWOLF'],
                          'address': 5350064,
                          'handler': 5109395,
                          'speed': None,
                          'lifetime': None},
 'MUTE_SCORPION_51A2F0': {'name': 'Pit Scorpion — Ballistic',
                          'faction': 'Evolved',
                          'units': ['UNIT_MUTE_SCORPION'],
                          'address': 5350128,
                          'handler': 5117869,
                          'speed': 1280,
                          'lifetime': None},
 'MUTE_CRINOID_51A330': {'name': 'Crinoid — Instant / hitscan',
                         'faction': 'Evolved',
                         'units': ['UNIT_MUTE_CRINOID'],
                         'address': 5350192,
                         'handler': 5109395,
                         'speed': None,
                         'lifetime': None},
 'MUTE_MASTODON_51A370': {'name': 'War Mastodon — Direct projectile',
                          'faction': 'Evolved',
                          'units': ['UNIT_MUTE_MASTODON'],
                          'address': 5350256,
                          'handler': 5116456,
                          'speed': 1536,
                          'lifetime': None},
 'MUTE_HIPPO_51A3B0': {'name': 'Death Hippo — Direct projectile',
                       'faction': 'Evolved',
                       'units': ['UNIT_MUTE_HIPPO'],
                       'address': 5350320,
                       'handler': 5116456,
                       'speed': 1792,
                       'lifetime': None},
 'MUTE_CRAB_51A3F0': {'name': 'Missile Crab — Artillery',
                      'faction': 'Evolved',
                      'units': ['UNIT_MUTE_CRAB'],
                      'address': 5350384,
                      'handler': 5112123,
                      'speed': None,
                      'lifetime': None},
 'MUTE_BEETLE_51A430': {'name': 'Mega Beetle — Ballistic',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_BEETLE'],
                        'address': 5350448,
                        'handler': 5117869,
                        'speed': 1280,
                        'lifetime': None},
 'ROBOT_PATROLBOT_51A470': {'name': 'Patrolbot — Instant / hitscan',
                            'faction': 'Series 9',
                            'units': ['UNIT_ROBOT_PATROLBOT'],
                            'address': 5350512,
                            'handler': 5109395,
                            'speed': None,
                            'lifetime': None},
 'ROBOT_RESPONSEBOT_51A4B0': {'name': 'Responsebot — Instant / hitscan',
                              'faction': 'Series 9',
                              'units': ['UNIT_ROBOT_RESPONSEBOT'],
                              'address': 5350576,
                              'handler': 5109395,
                              'speed': None,
                              'lifetime': None},
 'ROBOT_RADIATOR_51A4F0': {'name': 'Radiator — Radiation effect',
                           'faction': 'Series 9',
                           'units': ['UNIT_ROBOT_RADIATOR'],
                           'address': 5350640,
                           'handler': 5124530,
                           'speed': None,
                           'lifetime': None},
 'ROBOT_TANKBOT_51A530': {'name': 'Tankbot — Ballistic',
                          'faction': 'Series 9',
                          'units': ['UNIT_ROBOT_TANKBOT'],
                          'address': 5350704,
                          'handler': 5117869,
                          'speed': 1536,
                          'lifetime': None},
 'ROBOT_DOOMDOME_51A570': {'name': 'Doom Dome — Direct projectile',
                           'faction': 'Series 9',
                           'units': ['UNIT_ROBOT_DOOMDOME'],
                           'address': 5350768,
                           'handler': 5116456,
                           'speed': 1024,
                           'lifetime': None},
 'ROBOT_CAUTERISER_51A5B0': {'name': 'Cauteriser — Special effect',
                             'faction': 'Series 9',
                             'units': ['UNIT_ROBOT_CAUTERISER'],
                             'address': 5350832,
                             'handler': 5126841,
                             'speed': None,
                             'lifetime': None},
 'ROBOT_GRIMREAPER_51A5F0': {'name': 'Grim Reaper — Instant / hitscan',
                             'faction': 'Series 9',
                             'units': ['UNIT_ROBOT_GRIMREAPER'],
                             'address': 5350896,
                             'handler': 5109395,
                             'speed': None,
                             'lifetime': None},
 'SURV_TOWER1_51A630': {'name': 'Sentry Gun — Direct projectile',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_TOWER1'],
                        'address': 5350960,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'SURV_TOWER2_51A670': {'name': 'Cannon Tower — Direct projectile',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_TOWER2'],
                        'address': 5351024,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'SURV_TOWER3_51A6B0': {'name': 'AA Tower — Homing missile',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_TOWER3'],
                        'address': 5351088,
                        'handler': 5118937,
                        'speed': 1536,
                        'lifetime': 34},
 'SURV_TOWER4_51A6F0': {'name': 'Laser Destroyer — Direct projectile',
                        'faction': 'Survivors',
                        'units': ['UNIT_SURV_TOWER4'],
                        'address': 5351152,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'MUTE_TOWER1_51A730': {'name': 'Kneecapper — Direct projectile',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_TOWER1'],
                        'address': 5351216,
                        'handler': 5116456,
                        'speed': 1536,
                        'lifetime': None},
 'MUTE_TOWER2_51A770': {'name': 'The Worm — Direct projectile',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_TOWER2'],
                        'address': 5351280,
                        'handler': 5116456,
                        'speed': 1280,
                        'lifetime': None},
 'MUTE_TOWER3_51A7B0': {'name': 'Bazooka Battery — Homing missile',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_TOWER3'],
                        'address': 5351344,
                        'handler': 5118937,
                        'speed': 1536,
                        'lifetime': 34},
 'MUTE_TOWER4_51A7F0': {'name': 'Touch of Death — Special effect',
                        'faction': 'Evolved',
                        'units': ['UNIT_MUTE_TOWER4'],
                        'address': 5351408,
                        'handler': 5126910,
                        'speed': None,
                        'lifetime': None},
 'ROBOT_TOWER1_51A830': {'name': 'Distance Seeder — Direct projectile',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_TOWER1'],
                         'address': 5351472,
                         'handler': 5116456,
                         'speed': 1024,
                         'lifetime': None},
 'ROBOT_TOWER2_51A870': {'name': 'Pod Cannon — Homing missile',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_TOWER2'],
                         'address': 5351536,
                         'handler': 5118937,
                         'speed': 1280,
                         'lifetime': 34},
 'ROBOT_TOWER3_51A8B0': {'name': 'Solar Intensifier — Homing missile',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_TOWER3'],
                         'address': 5351600,
                         'handler': 5118937,
                         'speed': 1536,
                         'lifetime': 34},
 'ROBOT_TOWER4_51A8F0': {'name': 'Lightning Generator — Special effect',
                         'faction': 'Series 9',
                         'units': ['UNIT_ROBOT_TOWER4'],
                         'address': 5351664,
                         'handler': 5126886,
                         'speed': None,
                         'lifetime': None},
 'SURV_AIR1_51A9F0': {'name': 'Orville Fighter — Instant / hitscan',
                      'faction': 'Survivors',
                      'units': ['UNIT_SURV_AIR1'],
                      'address': 5351920,
                      'handler': 5109395,
                      'speed': None,
                      'lifetime': None},
 'SURV_AIR2_51AA30': {'name': 'Wilbur Bomber — Bomb',
                      'faction': 'Survivors',
                      'units': ['UNIT_SURV_AIR2'],
                      'address': 5351984,
                      'handler': 5110963,
                      'speed': 512,
                      'lifetime': None},
 'MUTE_AIR1_51AA70': {'name': 'Pteranodon — Instant / hitscan',
                      'faction': 'Evolved',
                      'units': ['UNIT_MUTE_AIR1'],
                      'address': 5352048,
                      'handler': 5109395,
                      'speed': None,
                      'lifetime': None},
 'MUTE_AIR2_51AAB0': {'name': 'Wasp Bomber — Bomb',
                      'faction': 'Evolved',
                      'units': ['UNIT_MUTE_AIR2'],
                      'address': 5352112,
                      'handler': 5110963,
                      'speed': 512,
                      'lifetime': None},
 'ROBOT_AIR1_51AAF0': {'name': 'AG-Responsebot Fighter — Instant / hitscan',
                       'faction': 'Series 9',
                       'units': ['UNIT_ROBOT_AIR1'],
                       'address': 5352176,
                       'handler': 5109395,
                       'speed': None,
                       'lifetime': None},
 'ROBOT_AIR2_51AB30': {'name': 'Crop Duster Bomber — Bomb',
                       'faction': 'Series 9',
                       'units': ['UNIT_ROBOT_AIR2'],
                       'address': 5352240,
                       'handler': 5110963,
                       'speed': 512,
                       'lifetime': None}}
