"""Verified stock KWIPv3 tier lists; addresses tied to the supported EXE hash."""

UNLOCKS = {'UNIT_SURV_GUNNER': {'default': 0,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 6,
                      'producer': 'Barracks',
                      'category': 'Infantry'},
 'UNIT_SURV_GRENADIER': {'default': 1,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 9,
                         'producer': 'Barracks',
                         'category': 'Infantry'},
 'UNIT_SURV_FLAMER': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 12,
                      'producer': 'Barracks',
                      'category': 'Infantry'},
 'UNIT_SURV_ROCKETEER': {'default': 3,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 15,
                         'producer': 'Barracks',
                         'category': 'Infantry'},
 'UNIT_SURV_SNIPER': {'default': 5,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 18,
                      'producer': 'Barracks',
                      'category': 'Infantry'},
 'UNIT_SURV_TECHNICIAN': {'default': 0,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 21,
                          'producer': 'Barracks',
                          'category': 'Infantry'},
 'UNIT_SURV_KAMIKAZE': {'default': 4,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 24,
                        'producer': 'Barracks',
                        'category': 'Infantry'},
 'UNIT_MUTE_GUNNER': {'default': 0,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 7,
                      'producer': 'Warrior Hall',
                      'category': 'Infantry'},
 'UNIT_MUTE_GRENADIER': {'default': 1,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 10,
                         'producer': 'Warrior Hall',
                         'category': 'Infantry'},
 'UNIT_MUTE_FLAMER': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 13,
                      'producer': 'Warrior Hall',
                      'category': 'Infantry'},
 'UNIT_MUTE_ROCKETEER': {'default': 3,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 16,
                         'producer': 'Warrior Hall',
                         'category': 'Infantry'},
 'UNIT_MUTE_SNIPER': {'default': 5,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 19,
                      'producer': 'Warrior Hall',
                      'category': 'Infantry'},
 'UNIT_MUTE_TECHNICIAN': {'default': 0,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 22,
                          'producer': 'Warrior Hall',
                          'category': 'Infantry'},
 'UNIT_MUTE_KAMIKAZE': {'default': 4,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 25,
                        'producer': 'Warrior Hall',
                        'category': 'Infantry'},
 'UNIT_ROBOT_GUNNER': {'default': 0,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 8,
                       'producer': 'Microunit Factory',
                       'category': 'Infantry'},
 'UNIT_ROBOT_GRENADIER': {'default': 1,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 11,
                          'producer': 'Microunit Factory',
                          'category': 'Infantry'},
 'UNIT_ROBOT_FLAMER': {'default': 2,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 14,
                       'producer': 'Microunit Factory',
                       'category': 'Infantry'},
 'UNIT_ROBOT_ROCKETEER': {'default': 3,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 17,
                          'producer': 'Microunit Factory',
                          'category': 'Infantry'},
 'UNIT_ROBOT_SNIPER': {'default': 5,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 20,
                       'producer': 'Microunit Factory',
                       'category': 'Infantry'},
 'UNIT_ROBOT_TECHNICIAN': {'default': 0,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 23,
                           'producer': 'Microunit Factory',
                           'category': 'Infantry'},
 'UNIT_ROBOT_KAMIKAZE': {'default': 4,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 26,
                         'producer': 'Microunit Factory',
                         'category': 'Infantry'},
 'UNIT_SURV_MOBILEOUTPOST': {'default': 5,
                             'minimum': 0,
                             'maximum': 5,
                             'enum': 42,
                             'producer': 'Machine Shop',
                             'category': 'Vehicles'},
 'UNIT_SURV_MOBILEDRILLRIG': {'default': 0,
                              'minimum': 0,
                              'maximum': 5,
                              'enum': 45,
                              'producer': 'Machine Shop',
                              'category': 'Vehicles'},
 'UNIT_SURV_TANKER': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 48,
                      'producer': 'Machine Shop',
                      'category': 'Vehicles'},
 'UNIT_SURV_BIKE': {'default': 0,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 51,
                    'producer': 'Machine Shop',
                    'category': 'Vehicles'},
 'UNIT_SURV_HOVERBUGGY': {'default': 1,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 52,
                          'producer': 'Machine Shop',
                          'category': 'Vehicles'},
 'UNIT_SURV_ATV': {'default': 0,
                   'minimum': 0,
                   'maximum': 5,
                   'enum': 53,
                   'producer': 'Machine Shop',
                   'category': 'Vehicles'},
 'UNIT_SURV_ANACONDATANK': {'default': 2,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 54,
                            'producer': 'Machine Shop',
                            'category': 'Vehicles'},
 'UNIT_SURV_BARRAGECRAFT': {'default': 3,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 55,
                            'producer': 'Machine Shop',
                            'category': 'Vehicles'},
 'UNIT_SURV_AUTOCANNONTANK': {'default': 4,
                              'minimum': 0,
                              'maximum': 5,
                              'enum': 56,
                              'producer': 'Machine Shop',
                              'category': 'Vehicles'},
 'UNIT_SURV_JUGGERNAUT': {'default': 5,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 57,
                          'producer': 'Machine Shop',
                          'category': 'Vehicles'},
 'UNIT_MUTE_MOBILEOUTPOST': {'default': 5,
                             'minimum': 0,
                             'maximum': 5,
                             'enum': 43,
                             'producer': 'Beast Enclosure',
                             'category': 'Vehicles'},
 'UNIT_MUTE_MOBILEDRILLRIG': {'default': 0,
                              'minimum': 0,
                              'maximum': 5,
                              'enum': 46,
                              'producer': 'Beast Enclosure',
                              'category': 'Vehicles'},
 'UNIT_MUTE_TANKER': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 49,
                      'producer': 'Beast Enclosure',
                      'category': 'Vehicles'},
 'UNIT_MUTE_DIREWOLF': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 58,
                        'producer': 'Beast Enclosure',
                        'category': 'Vehicles'},
 'UNIT_MUTE_SCORPION': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 59,
                        'producer': 'Beast Enclosure',
                        'category': 'Vehicles'},
 'UNIT_MUTE_CRINOID': {'default': 1,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 60,
                       'producer': 'Beast Enclosure',
                       'category': 'Vehicles'},
 'UNIT_MUTE_MASTODON': {'default': 2,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 61,
                        'producer': 'Beast Enclosure',
                        'category': 'Vehicles'},
 'UNIT_MUTE_HIPPO': {'default': 3,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 62,
                     'producer': 'Beast Enclosure',
                     'category': 'Vehicles'},
 'UNIT_MUTE_CRAB': {'default': 4,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 63,
                    'producer': 'Beast Enclosure',
                    'category': 'Vehicles'},
 'UNIT_MUTE_BEETLE': {'default': 5,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 64,
                      'producer': 'Beast Enclosure',
                      'category': 'Vehicles'},
 'UNIT_ROBOT_MOBILEOUTPOST': {'default': 5,
                              'minimum': 0,
                              'maximum': 5,
                              'enum': 44,
                              'producer': 'Macrounit Factory',
                              'category': 'Vehicles'},
 'UNIT_ROBOT_MOBILEDRILLRIG': {'default': 0,
                               'minimum': 0,
                               'maximum': 5,
                               'enum': 47,
                               'producer': 'Macrounit Factory',
                               'category': 'Vehicles'},
 'UNIT_ROBOT_TANKER': {'default': 2,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 50,
                       'producer': 'Macrounit Factory',
                       'category': 'Vehicles'},
 'UNIT_ROBOT_PATROLBOT': {'default': 0,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 65,
                          'producer': 'Macrounit Factory',
                          'category': 'Vehicles'},
 'UNIT_ROBOT_RESPONSEBOT': {'default': 0,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 66,
                            'producer': 'Macrounit Factory',
                            'category': 'Vehicles'},
 'UNIT_ROBOT_RADIATOR': {'default': 1,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 67,
                         'producer': 'Macrounit Factory',
                         'category': 'Vehicles'},
 'UNIT_ROBOT_TANKBOT': {'default': 2,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 68,
                        'producer': 'Macrounit Factory',
                        'category': 'Vehicles'},
 'UNIT_ROBOT_DOOMDOME': {'default': 3,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 69,
                         'producer': 'Macrounit Factory',
                         'category': 'Vehicles'},
 'UNIT_ROBOT_CAUTERISER': {'default': 4,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 70,
                           'producer': 'Macrounit Factory',
                           'category': 'Vehicles'},
 'UNIT_ROBOT_GRIMREAPER': {'default': 5,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 71,
                           'producer': 'Macrounit Factory',
                           'category': 'Vehicles'},
 'UNIT_SURV_OUTPOST': {'default': 0,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 72,
                       'producer': 'Outpost',
                       'category': 'Buildings'},
 'UNIT_SURV_BARRACKS': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 75,
                        'producer': 'Outpost',
                        'category': 'Buildings'},
 'UNIT_SURV_MACHINESHOP': {'default': 0,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 78,
                           'producer': 'Outpost',
                           'category': 'Buildings'},
 'UNIT_SURV_ARMOURY': {'default': 0,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 81,
                       'producer': 'Outpost',
                       'category': 'Buildings'},
 'UNIT_SURV_POWERSTATION': {'default': 0,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 84,
                            'producer': 'Outpost',
                            'category': 'Buildings'},
 'UNIT_SURV_CONVERTER': {'default': 5,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 90,
                         'producer': 'Outpost',
                         'category': 'Buildings'},
 'UNIT_SURV_COLLECTOR': {'default': 3,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 93,
                         'producer': 'Outpost',
                         'category': 'Buildings'},
 'UNIT_SURV_REPAIRBAY': {'default': 1,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 96,
                         'producer': 'Outpost',
                         'category': 'Buildings'},
 'UNIT_SURV_RESEARCHLAB': {'default': 0,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 99,
                           'producer': 'Outpost',
                           'category': 'Buildings'},
 'UNIT_MUTE_OUTPOST': {'default': 0,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 73,
                       'producer': 'Clanhall',
                       'category': 'Buildings'},
 'UNIT_MUTE_BARRACKS': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 76,
                        'producer': 'Clanhall',
                        'category': 'Buildings'},
 'UNIT_MUTE_MACHINESHOP': {'default': 0,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 79,
                           'producer': 'Clanhall',
                           'category': 'Buildings'},
 'UNIT_MUTE_ARMOURY': {'default': 0,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 82,
                       'producer': 'Clanhall',
                       'category': 'Buildings'},
 'UNIT_MUTE_POWERSTATION': {'default': 0,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 85,
                            'producer': 'Clanhall',
                            'category': 'Buildings'},
 'UNIT_MUTE_CONVERTER': {'default': 5,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 91,
                         'producer': 'Clanhall',
                         'category': 'Buildings'},
 'UNIT_MUTE_COLLECTOR': {'default': 3,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 94,
                         'producer': 'Clanhall',
                         'category': 'Buildings'},
 'UNIT_MUTE_REPAIRBAY': {'default': 1,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 97,
                         'producer': 'Clanhall',
                         'category': 'Buildings'},
 'UNIT_MUTE_RESEARCHLAB': {'default': 0,
                           'minimum': 0,
                           'maximum': 5,
                           'enum': 100,
                           'producer': 'Clanhall',
                           'category': 'Buildings'},
 'UNIT_TEMPLE': {'default': 5,
                 'minimum': 0,
                 'maximum': 5,
                 'enum': 102,
                 'producer': 'Clanhall',
                 'category': 'Buildings'},
 'UNIT_ROBOT_OUTPOST': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 74,
                        'producer': 'Barn',
                        'category': 'Buildings'},
 'UNIT_ROBOT_BARRACKS': {'default': 0,
                         'minimum': 0,
                         'maximum': 5,
                         'enum': 77,
                         'producer': 'Barn',
                         'category': 'Buildings'},
 'UNIT_ROBOT_MACHINESHOP': {'default': 0,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 80,
                            'producer': 'Barn',
                            'category': 'Buildings'},
 'UNIT_ROBOT_ARMOURY': {'default': 0,
                        'minimum': 0,
                        'maximum': 5,
                        'enum': 83,
                        'producer': 'Barn',
                        'category': 'Buildings'},
 'UNIT_ROBOT_POWERSTATION': {'default': 0,
                             'minimum': 0,
                             'maximum': 5,
                             'enum': 86,
                             'producer': 'Barn',
                             'category': 'Buildings'},
 'UNIT_ROBOT_CONVERTER': {'default': 5,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 92,
                          'producer': 'Barn',
                          'category': 'Buildings'},
 'UNIT_ROBOT_COLLECTOR': {'default': 3,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 95,
                          'producer': 'Barn',
                          'category': 'Buildings'},
 'UNIT_ROBOT_REPAIRBAY': {'default': 1,
                          'minimum': 0,
                          'maximum': 5,
                          'enum': 98,
                          'producer': 'Barn',
                          'category': 'Buildings'},
 'UNIT_ROBOT_RESEARCHLAB': {'default': 0,
                            'minimum': 0,
                            'maximum': 5,
                            'enum': 101,
                            'producer': 'Barn',
                            'category': 'Buildings'},
 'UNIT_SURV_TOWER1': {'default': 1,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 103,
                      'producer': 'Armoury',
                      'category': 'Defences'},
 'UNIT_SURV_TOWER2': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 106,
                      'producer': 'Armoury',
                      'category': 'Defences'},
 'UNIT_SURV_TOWER3': {'default': 3,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 109,
                      'producer': 'Armoury',
                      'category': 'Defences'},
 'UNIT_SURV_TOWER4': {'default': 4,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 112,
                      'producer': 'Armoury',
                      'category': 'Defences'},
 'UNIT_MUTE_TOWER1': {'default': 1,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 104,
                      'producer': 'Forge',
                      'category': 'Defences'},
 'UNIT_MUTE_TOWER2': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 107,
                      'producer': 'Forge',
                      'category': 'Defences'},
 'UNIT_MUTE_TOWER3': {'default': 3,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 110,
                      'producer': 'Forge',
                      'category': 'Defences'},
 'UNIT_MUTE_TOWER4': {'default': 4,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 113,
                      'producer': 'Forge',
                      'category': 'Defences'},
 'UNIT_ROBOT_TOWER1': {'default': 1,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 105,
                       'producer': 'Weapon Control',
                       'category': 'Defences'},
 'UNIT_ROBOT_TOWER2': {'default': 2,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 108,
                       'producer': 'Weapon Control',
                       'category': 'Defences'},
 'UNIT_ROBOT_TOWER3': {'default': 3,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 111,
                       'producer': 'Weapon Control',
                       'category': 'Defences'},
 'UNIT_ROBOT_TOWER4': {'default': 4,
                       'minimum': 0,
                       'maximum': 5,
                       'enum': 114,
                       'producer': 'Weapon Control',
                       'category': 'Defences'},
 'UNIT_SURV_AIR1': {'default': 5,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 124,
                    'producer': 'Machine Shop',
                    'category': 'Vehicles'},
 'UNIT_SURV_AIR2': {'default': 5,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 127,
                    'producer': 'Machine Shop',
                    'category': 'Vehicles'},
 'UNIT_SURV_AIR3': {'default': 4,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 130,
                    'producer': 'Machine Shop',
                    'category': 'Vehicles'},
 'UNIT_MUTE_AIR1': {'default': 5,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 125,
                    'producer': 'Beast Enclosure',
                    'category': 'Vehicles'},
 'UNIT_MUTE_AIR2': {'default': 5,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 128,
                    'producer': 'Beast Enclosure',
                    'category': 'Vehicles'},
 'UNIT_MUTE_AIR3': {'default': 4,
                    'minimum': 0,
                    'maximum': 5,
                    'enum': 131,
                    'producer': 'Beast Enclosure',
                    'category': 'Vehicles'},
 'UNIT_ROBOT_AIR1': {'default': 5,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 126,
                     'producer': 'Macrounit Factory',
                     'category': 'Vehicles'},
 'UNIT_ROBOT_AIR2': {'default': 5,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 129,
                     'producer': 'Macrounit Factory',
                     'category': 'Vehicles'},
 'UNIT_ROBOT_AIR3': {'default': 4,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 132,
                     'producer': 'Macrounit Factory',
                     'category': 'Vehicles'},
 'UNIT_SURV_WALL1': {'default': 2,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 115,
                     'producer': 'Outpost',
                     'category': 'Buildings'},
 'UNIT_SURV_WALL2': {'default': 4,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 118,
                     'producer': 'Outpost',
                     'category': 'Buildings'},
 'UNIT_MUTE_WALL1': {'default': 2,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 116,
                     'producer': 'Clanhall',
                     'category': 'Buildings'},
 'UNIT_MUTE_WALL2': {'default': 4,
                     'minimum': 0,
                     'maximum': 5,
                     'enum': 119,
                     'producer': 'Clanhall',
                     'category': 'Buildings'},
 'UNIT_ROBOT_WALL1': {'default': 2,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 117,
                      'producer': 'Barn',
                      'category': 'Buildings'},
 'UNIT_ROBOT_WALL2': {'default': 4,
                      'minimum': 0,
                      'maximum': 5,
                      'enum': 120,
                      'producer': 'Barn',
                      'category': 'Buildings'}}

TABLES = {5302364: [[(51, 58, 65), (53, 59, 66), (45, 46, 47)],
           [(52, 60, 67), (1039, 1039, 1039), (1034, 1034, 1034)],
           [(48, 49, 50), (54, 61, 68), (1035, 1035, 1035), (1037, 1037, 1037)],
           [(1040, 1040, 1040), (55, 62, 69)],
           [(130, 131, 132), (1041, 1041, 1041), (1038, 1038, 1038), (56, 63, 70)],
           [(124, 125, 126), (127, 128, 129), (1036, 1036, 1036), (57, 64, 71), (42, 43, 44)]],
 5259672: [[(6, 7, 8), (21, 22, 23)],
           [(9, 10, 11)],
           [(12, 13, 14)],
           [(15, 16, 17)],
           [(24, 25, 26)],
           [(18, 19, 20)]],
 5345628: [[(72, 73, 74),
            (75, 76, 77),
            (78, 79, 80),
            (81, 82, 83),
            (99, 100, 101),
            (84, 85, 86),
            (99, 100, 101)],
           [(96, 97, 98)],
           [(115, 116, 117)],
           [(93, 94, 95)],
           [(118, 119, 120)],
           [(90, 91, 92), (65535, 102, 65535)]],
 5259424: [[], [(103, 104, 105)], [(106, 107, 108)], [(109, 110, 111)], [(112, 113, 114)], []]}

ORIGINAL = {a: bytes.fromhex(h) for a, h in {5302364: 'b4e75000cce75000e4e7500004e8500018e8500038e85000',
 5302196: '33003a00410035003b0042002d002e002f00ffffffffffff',
 5302220: '34003c0043000f040f040f040a040a040a04ffffffffffff',
 5302244: '30003100320036003d0044000b040b040b040d040d040d04ffffffffffff',
 5302276: '10041004100437003e004500ffffffffffff',
 5302296: '8200830084001104110411040e040e040e0438003f004600ffffffffffff',
 5302328: '7c007d007e007f00800081000c040c040c043900400047002a002b002c00ffffffffffff',
 5259672: '484150005c4150006841500074415000804150008c415000',
 5259592: '060007000800150016001700ffffffffffff',
 5259612: '09000a000b00ffffffffffff',
 5259624: '0c000d000e00ffffffffffff',
 5259636: '0f0010001100ffffffffffff',
 5259648: '180019001a00ffffffffffff',
 5259660: '120013001400ffffffffffff',
 5345628: 'e89051001891510024915100309151003c91510048915100',
 5345512: '480049004a004b004c004d004e004f005000510052005300630064006500540055005600630064006500ffffffffffff',
 5345560: '600061006200ffffffffffff',
 5345572: '730074007500ffffffffffff',
 5345584: '5d005e005f00ffffffffffff',
 5345596: '760077007800ffffffffffff',
 5345608: '5a005b005c00ffff6600ffffffffffffffff',
 5259424: '604050006840500074405000804050008c40500098405000',
 5259360: 'ffffffffffff',
 5259368: '670068006900ffffffffffff',
 5259380: '6a006b006c00ffffffffffff',
 5259392: '6d006e006f00ffffffffffff',
 5259404: '700071007200ffffffffffff',
 5259416: 'ffffffffffff'}.items()}
